name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      CI: true
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      DEV_MARITUR_HOME_MODULE: ${{ vars.DEV_MARITUR_HOME_MODULE }}
      DEV_MARITUR_ITINERARY_MODULE: ${{ vars.DEV_MARITUR_ITINERARY_MODULE }}
      DEV_MARITUR_USER_MODULE: ${{ vars.DEV_MARITUR_USER_MODULE }}
      DEV_MARITUR_BRANCH_MODULE: ${{ vars.DEV_MARITUR_BRANCH_MODULE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Más eficiente para CI/CD

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'  # Acelera las instalaciones

      - name: Install dependencies
        run: npm ci

      - name: Install TypeScript & Compile
        run: |
          npm install --save-dev typescript
          npx tsc --project tsconfig.json

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          npx playwright test

      - name: Set permissions for Playwright report (if exists)
        run: |
          if [ -d "playwright-report" ]; then
            chmod -R 777 playwright-report/
          fi

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()  # Asegura que se suba incluso si fallan los tests
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
