name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      CI: true
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      MARITUR_HOME_MODULE: ${{ vars.MARITUR_HOME_MODULE }}
      MARITUR_ITINERARY_MODULE: ${{ vars.MARITUR_ITINERARY_MODULE }}
      MARITUR_USER_MODULE: ${{ vars.MARITUR_USER_MODULE }}
      MARITUR_USER_MODULE_ADDUSER: ${{ vars.MARITUR_USER_MODULE_ADDUSER }}
      MARITUR_BRANCH_MODULE: ${{ vars.MARITUR_BRANCH_MODULE }}
      MARITUR_SERVICE_MODULE: ${{ vars.MARITUR_SERVICE_MODULE }}
      MARITUR_DOCUMENT_MODULE: ${{ vars.MARITUR_DOCUMENT_MODULE }}
      MARITUR_ROLE_MODULE: ${{ vars.MARITUR_ROLE_MODULE }}
      MARITUR_SUPPLIER_MODULE: ${{ vars.MARITUR_SUPPLIER_MODULE }}
      MARITUR_BANKACCOUNT_MODULE: ${{ vars.MARITUR_BANKACCOUNT_MODULE }}
      MARITUR_CONCESSIONAIRE_MODULE: ${{ vars.MARITUR_CONCESSIONAIRE_MODULE }}
      MARITUR_CLIENT_MODULE: ${{ vars.MARITUR_CLIENT_MODULE }}
      MARITUR_HOTEL_MODULE: ${{ vars.MARITUR_HOTEL_MODULE }}
      MARITUR_CONFIG_MODULE: ${{ vars.MARITUR_CONFIG_MODULE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Más eficiente para CI/CD

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Verify environment variables
        run: env | grep MARITUR  

      - name: Install TypeScript & Compile
        run: |
          npm install --save-dev typescript
          npx tsc --project tsconfig.json

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true

      - name: Generate Allure Report
        run: npx allure generate test-results/ --clean -o allure-report
     
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
